name: publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: guides
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    
    - name: Install AsciiDoctor
      run: gem install asciidoctor asciidoctor-pdf --pre

    - name: Install linkchecker
      run: pip install linkchecker

    - name: Clean the environment
      run: make clean

    - name: Build HTML
      run: |
        make html BUILD=foreman
        make html BUILD=foreman-deb
        make html BUILD=satellite

    - name: Check HTML links
      run: |
        make linkchecker BUILD=foreman
        make linkchecker BUILD=foreman-deb
        make linkchecker BUILD=satellite

    - name: Build PDF
      run: |
        make pdf BUILD=foreman
        make pdf BUILD=foreman-deb
        make pdf BUILD=satellite
