name: publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: guides
    steps:
    - uses: actions/checkout@v2
    
    - name: Install AsciiDoctor
      run: gem install asciidoctor

    - name: Clean the environment
      run: make clean

    - name: Build HTML
      run: |
        make html BUILD=foreman
        make html BUILD=foreman-deb
        make html BUILD=satellite
